import { UserProfile, WorkoutPlan, NutritionPlan, UserStats } from '../types';

export const demoUser: UserProfile = {
  id: 'usr_alex_01',
  name: 'Alex',
  email: 'alex.vance@fitverse.ai',
  age: 25,
  gender: 'Male',
  heightCm: 178,
  weightKg: 74.5,
  activityLevel: 'Athlete',
  primaryGoal: 'Build',
  environment: 'Commercial Facility',
  equipment: ['Barbell', 'Dumbbells', 'Cables', 'Bench'],
  workoutDuration: 45,
  nutritionStyle: 'Omnivore',
  restrictions: ['Gluten Free'],
  premium: true,
  streakDays: 14,
  joinedDate: '2026-01-15',
  currentPhase: 'Hypertrophy Phase II',
};

export const demoWorkout: WorkoutPlan = {
  id: 'plan_hypertrophy_v4',
  name: 'Hypertrophy Core V.4',
  phase: 'Hypertrophy Phase II',
  durationMinutes: 45,
  calories: 450,
  difficulty: 'Advanced',
  targetMuscles: ['Chest', 'Shoulders', 'Triceps'],
  aiPrediction: 'Expected 1RM Increase: +2.5%',
  exercises: [
    {
      id: 'ex_1',
      name: 'Barbell Bench Press',
      primaryMuscle: 'Chest',
      sets: 4,
      reps: '8–10',
      restSeconds: 90,
      targetWeight: 225,
      completedSets: 1,
      instructions: [
        'Retract scapula and maintain a solid arch.',
        'Lower bar with control to lower chest.',
        'Explode upward while pressing heels into the floor.',
      ],
    },
    {
      id: 'ex_2',
      name: 'Seated Dumbbell Press',
      primaryMuscle: 'Shoulders',
      sets: 4,
      reps: '10–12',
      restSeconds: 60,
      targetWeight: 65,
      completedSets: 0,
      instructions: [
        'Keep wrists neutral over elbows.',
        'Press weights overhead without locking out sharply.',
      ],
    },
    {
      id: 'ex_3',
      name: 'Incline Cable Flyes',
      primaryMuscle: 'Chest',
      sets: 3,
      reps: '12–15',
      restSeconds: 45,
      targetWeight: 40,
      completedSets: 0,
      instructions: [
        'Set bench to 30 degrees angle.',
        'Focus on deep chest stretch at bottom and strong peak squeeze.',
      ],
    },
    {
      id: 'ex_4',
      name: 'Barbell Deadlift',
      primaryMuscle: 'Back / Posterior',
      sets: 4,
      reps: '8–10',
      restSeconds: 90,
      targetWeight: 315,
      completedSets: 0,
      instructions: [
        'Hinge at hips, brace core rigidly, and pull slack out of the bar.',
        'Drive through heels and push hips forward to lockout.',
      ],
    },
    {
      id: 'ex_5',
      name: 'Bent Over Rows',
      primaryMuscle: 'Upper Back',
      sets: 4,
      reps: '12',
      restSeconds: 60,
      targetWeight: 185,
      completedSets: 0,
      instructions: [
        'Maintain a 45-degree spine angle.',
        'Pull elbows toward hips and squeeze lats.',
      ],
    },
  ],
};

export const demoNutrition: NutritionPlan = {
  id: 'nutr_plan_01',
  calories: 2400,
  proteinGrams: 180,
  carbsGrams: 220,
  fatsGrams: 65,
  consumedCalories: 1840,
  consumedProtein: 120,
  consumedCarbs: 160,
  consumedFats: 45,
  hydrationLiters: 1.2,
  hydrationTargetLiters: 3.0,
  meals: [
    {
      id: 'meal_1',
      type: 'Breakfast',
      name: 'Anabolic Oat Bowl',
      description: 'Rolled gluten-free oats, pure whey isolate, blueberries, chia seeds, almond butter.',
      calories: 620,
      protein: 48,
      carbs: 72,
      fats: 16,
      ingredients: ['Gluten-Free Oats', 'Whey Isolate', 'Wild Blueberries', 'Chia Seeds', 'Almond Butter'],
    },
    {
      id: 'meal_2',
      type: 'Lunch',
      name: 'Performance Chicken Bowl',
      description: 'Charred free-range chicken breast, fluffy quinoa, sweet potato cubes, chimichurri.',
      calories: 780,
      protein: 62,
      carbs: 74,
      fats: 22,
      ingredients: ['Chicken Breast 250g', 'Quinoa 150g', 'Sweet Potato', 'Extra Virgin Olive Oil'],
    },
    {
      id: 'meal_3',
      type: 'Dinner',
      name: 'Wild Salmon & Asparagus',
      description: 'Crisp-skinned wild salmon fillet, steamed jasmine rice, charred garlic asparagus.',
      calories: 710,
      protein: 52,
      carbs: 56,
      fats: 24,
      ingredients: ['Wild Salmon 200g', 'Jasmine Rice', 'Asparagus Spears', 'Garlic Herb Butter'],
    },
    {
      id: 'meal_4',
      type: 'Snack',
      name: 'Greek Yogurt & Honey Crisp',
      description: 'Double-strained Greek yogurt, raw wildflower honey, crushed raw walnuts.',
      calories: 290,
      protein: 24,
      carbs: 22,
      fats: 9,
      ingredients: ['0% Greek Yogurt 200g', 'Raw Honey', 'Walnuts 15g'],
    },
  ],
};

export const demoStats: UserStats = {
  consistencyScore: 94,
  consistencyChange: 2,
  totalWorkoutsCompleted: 12,
  totalWorkoutsTarget: 16,
  averageBurnKcal: 640,
  currentStreakDays: 14,
  dailyGoalCompletionPercent: 78,
  heartRateBpm: 68,
  stepsCurrent: 8432,
  stepsTarget: 10000,
  sleepDuration: '7h 12m',
  sleepQuality: 'Optimal',
  weeklyOutputPercent: 75,
  weightTrend: [
    { date: 'Sep 10', weightKg: 75.8 },
    { date: 'Sep 17', weightKg: 75.4 },
    { date: 'Sep 24', weightKg: 75.0 },
    { date: 'Oct 01', weightKg: 74.7 },
    { date: 'Oct 05', weightKg: 74.5 },
  ],
  aiInsight: {
    headline: 'Recovery Rate is Optimal',
    details: 'Based on 14 analyzed sessions, your central nervous system recovery has peaked.',
    recommendation: 'Suggest increasing volume on lower body days by +5% next week.',
    confidence: 96,
  },
};
